spring:
  application:
    name: "Blue Velvet Music Store"
  datasource:
    username: rodrigo
    password: 123456
    url: jdbc:mysql://localhost:3307/db
    driver-class-name: com.mysql.cj.jdbc.Driver